name: bureauforever-classroleselector
services:
  bot:
    build: .
    image: wow-roles-bot:latest
    container_name: wow-roles-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
